name: Build and Push to ECR

on:
  push:
    branches: [ main ]

env:
  AWS_REGION: eu-north-1
  ECR_REPOSITORY: swiggy-ui

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      # AWS login
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-north-1

      # Login to ECR
      - name: Login to ECR
        run: |
          aws ecr get-login-password --region eu-north-1 \
          | docker login --username AWS --password-stdin ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.eu-north-1.amazonaws.com

      # Build image
      - name: Build Docker image
        run: docker build -t swiggy-ui .

      # Tag image
      - name: Tag image
        run: |
          docker tag swiggy-ui:latest \
          ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.eu-north-1.amazonaws.com/swiggy-ui:latest

      # Push image
      - name: Push image
        run: |
          docker push \
          ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.eu-north-1.amazonaws.com/swiggy-ui:latest
